spring:
  application:
    name: medflow
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: dev
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${OAUTH2_INTROSPECTION_URI:http://localhost:8085/realms/medflow/protocol/openid-connect/token/introspect}
          client-id: ${OAUTH2_CLIENT_ID:medflow-backend}
          client-secret: ${OAUTH2_CLIENT_SECRET:change-me}
        authorization:
          token-uri: ${OAUTH2_AUTHORIZATION_TOKEN_URI:http://localhost:8085/realms/medflow/protocol/openid-connect/token}
          audience: ${OAUTH2_AUTHORIZATION_AUDIENCE:${OAUTH2_CLIENT_ID:medflow-backend}}
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:medflow}}
    username: ${DB_USERNAME:medflow}
    password: ${DB_PASSWORD:medflow}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        '[default_schema]': ${DB_SCHEMA:medflow}
        '[format_sql]': true
    open-in-view: false

  flyway:
    enabled: true
    create-schemas: true
    default-schema: ${DB_SCHEMA:medflow}
    schemas: ${DB_SCHEMA:medflow}
    locations: classpath:migration

springdoc:
  api-docs:
    path: /api/openapi
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: true

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
